name: Clang-format Verification
on:
  push:
    branches:
    - main
    - dev
  pull_request:
    branches:
    - main
    - dev

jobs:
  format-checking:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run clang-format
        uses: jidicula/clang-format-action@v4.9.0
        with:
          clang-format-version: '18'
          check-path: 'chip8'